name: haiauto
description: "A SSET STUDENTS PROJECT"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #razorpay_flutter: ^1.3.5
  intl_phone_field: ^3.0.0
  http: ^1.2.2
  firebase_admin: ^0.3.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  shared_preferences: ^2.3.2 




shared_preferences_android:
path: ./relative/path/to/shared_preferences_android

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
  - assets/haiauto.png
  - assets/config.json
  #- assets/login_illustration.png
  - assets/config.json
  - assets/introduction1.png
  - assets/introduction2.png
  - assets/introduction3.png
  - assets/google_icon.png
  - assets/image.png
  - assets/map_placeholder.png
  



  
  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/CustomFont.ttf

android:
  app:
    src:
      main:
        res:
          mipmap-hdpi:
            ic_launcher.png: 'images/appicon.png'
